# Generated by Django 3.0.4 on 2020-03-07 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInformation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=180)),
                ('email', models.CharField(max_length=180)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=180)),
                ('website', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('signatory_first_name', models.CharField(max_length=30)),
                ('signatory_last_name', models.CharField(max_length=150)),
                ('signatory_signature', models.CharField(max_length=180)),
                ('witness_first_name', models.CharField(max_length=30)),
                ('witness_last_name', models.CharField(max_length=150)),
                ('witness_signature', models.CharField(max_length=180)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('billing_address', models.CharField(max_length=180)),
                ('shipping_address', models.CharField(max_length=180)),
                ('waiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order_manager.Waiver')),
                ('waiver_confirmation', models.BooleanField(default=False)),
                ('entryway_photo', models.ImageField(upload_to=order_manager.models.user_directory_path)),
                ('step_left_photo', models.ImageField(upload_to=order_manager.models.user_directory_path)),
                ('step_right_photo', models.ImageField(upload_to=order_manager.models.user_directory_path)),
                ('step_left_height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('step_right_height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ramp_colour', models.CharField(max_length=50)),
                ('delivery_method', models.CharField(max_length=50)),
                ('subsidize', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
