# Generated by Django 3.0.4 on 2020-03-08 21:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_manager', '0003_order_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientInformation',
            new_name='Client',
        ),
    ]
