# Generated by Django 3.0.4 on 2020-04-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0002_auto_20200401_0947'),
        ('order_manager', '0002_auto_20200401_0201'),
    ]

    operations = [
    ]
